version: "3.4"

services:
  cen:
    build:
      context: ../../..
      dockerfile: node/Dockerfile
      target: development
    container_name: cen-node
    command:  sh -c 'cd node/app && fresh'
    volumes:
      - ../../..:/go/src/gitlab.com/velo-labs/cen
      - $GOPATH/pkg/mod:/go/pkg/mod # to avoid re-"go mod download" on every build
    ports:
      - "8080:8080"
      - "6666:6666"
    environment:
      HORIZON_URL: "https://horizon-testnet.stellar.org"
      DRS_PUBLIC_KEY: "GBBKIWTP4MIMQJ6XDCXEUQCPXRO6KOFXTHVS6AMHN74BLPAM4ETL253J"
      DRS_SECRET_KEY: "SBZKPXN4VLJQJE6YGTRYTBYHWCKLGYH3WZ7XQRUANXO7XX6D6574PXYE"
      VELO_ISSUER_PUBLIC_KEY: "GC3COBQESTRET2AXK5ADR63L7LOMEZWDPODW4F2Z7Y44TTEOTRBSKXQ3"
      NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
